INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (1, 'Taylor Swift', 'Cruel Summer', 1468058171);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (2, 'Taylor Swift', 'Shake It Off', 1440936016);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (3, 'Taylor Swift', 'Love Story', 1452859410);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (4, 'Taylor Swift', 'You Belong With Me', 1452859427);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (5, 'Taylor Swift', 'Blank Space', 1440935808);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (6, 'Ariana Grande & The Weeknd', 'off the table (live from Vevo)', 1849204396);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (7, 'The Weeknd', 'Call Out My Name', 1363310482);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (8, 'The Weeknd', 'Blinding Lights', 1488408568);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (9, 'The Weeknd', 'Die For You', 1440872304);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (10, 'The Weeknd, JENNIE & Lily Rose Depp', 'One Of The Girls', 1693891139);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (11, 'Bad Bunny', 'NUEVAYoL', 1787022572);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (12, 'J Balvin & Bad Bunny', 'LA CANCIÓN', 1470146813);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (13, 'Bad Bunny', 'MIA (feat. Drake)', 1662168786);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (14, 'Bad Bunny & Bomba Estéreo', 'Ojitos Lindos', 1622045962);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (15, 'JHAYCO, J Balvin & Bad Bunny', 'No Me Conoce (Remix)', 1652080289);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (16, 'Drake', 'Hold On, We''re Going Home (feat. Majid Jordan)', 1440829630);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (17, 'Drake', 'One Dance (feat. Wizkid & Kyla)', 1440843496);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (18, 'Bad Bunny', 'MÍA (feat. Drake)', 1447555315);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (19, 'Drake', 'Hotline Bling', 1440841730);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (20, 'Still Woozy', 'Drake', 1572737688);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (21, 'Adele', 'Someone Like You', 1544491998);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (22, 'Adele', 'Set Fire to the Rain', 1544491988);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (23, 'Adele', 'Rolling in the Deep', 1544491233);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (24, 'Adele', 'Easy On Me', 1590036021);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (25, 'Adele', 'Hello', 1544494392);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (26, 'Ed Sheeran', 'Perfect', 1193701400);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (27, 'Ed Sheeran', 'Thinking Out Loud', 1050204631);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (28, 'Ed Sheeran', 'Shape of You', 1193701392);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (29, 'Ed Sheeran', 'Shivers', 1581087034);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (30, 'Ed Sheeran', 'Photograph', 1050204626);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (31, 'Beyoncé', 'Dance For You', 626205222);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (32, 'Beyoncé', 'Irreplaceable', 261707067);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (33, 'Beyoncé', 'Best Thing I Never Had', 626205875);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (34, 'Beyoncé', 'Love On Top', 626205216);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (35, 'Beyoncé', '1+1', 626205872);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (36, 'Coldplay', 'Yellow', 1122782283);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (37, 'Coldplay', 'Sparks', 1122782281);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (38, 'Coldplay', 'Viva La Vida', 1122773680);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (39, 'Coldplay', 'A Sky Full of Stars', 829910927);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (40, 'Coldplay', 'The Scientist', 1122776155);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (41, 'Billie Eilish', 'WILDFLOWER', 1739659144);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (42, 'Billie Eilish', 'BIRDS OF A FEATHER', 1739659142);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (43, 'Billie Eilish', 'ocean eyes', 1440899467);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (44, 'Billie Eilish & Khalid', 'lovely', 1369380479);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (45, 'Billie Eilish', 'What Was I Made For? (From The Motion Picture "Barbie")', 1696819855);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (46, 'Lady Gaga & Bruno Mars', 'Die With A Smile', 1762656732);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (47, 'Bruno Mars', 'When I Was Your Man', 573962555);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (48, 'Bruno Mars', '24K Magic', 1161504024);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (49, 'Mark Ronson', 'Uptown Funk (feat. Bruno Mars)', 943946671);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (50, 'Bruno Mars', 'That''s What I Like', 1161504043);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (51, 'Rihanna', 'Umbrella (feat. JAY-Z)', 1441154437);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (52, 'Rihanna', 'Don''t Stop The Music', 1441154439);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (53, 'Rihanna', 'Only Girl (In The World)', 1440896009);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (54, 'Rihanna', 'Diamonds', 1444321282);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (55, 'Rihanna', 'Disturbia', 1441154571);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (56, 'Post Malone', 'Circles', 1477880561);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (57, 'Post Malone & Swae Lee', 'Sunflower (Spider-Man: Into the Spider-Verse)', 1445949267);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (58, 'Morgan Wallen & Post Malone', 'I Ain''t Comin'' Back', 1802104420);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (59, 'Post Malone', 'Pour Me A Drink (feat. Blake Shelton)', 1752531909);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (60, 'Sam Feldt', 'Post Malone (feat. RANI)', 1462755255);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (61, 'Eminem', 'Lose Yourself', 1440903439);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (62, 'Eminem', 'Rap God', 1440864098);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (63, 'Eminem', 'Godzilla (feat. Juice WRLD)', 1495269629);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (64, 'Eminem', 'Without Me', 1440821643);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (65, 'Joeyy', 'Eminem', 1698162327);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (66, 'Shakira', 'Hips Don''t Lie (feat. Wyclef Jean)', 1817217063);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (67, 'Shakira', 'Whenever, Wherever', 188261029);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (68, 'Shakira', 'Waka Waka (Esto es Africa) [feat. Freshlyground]', 370711731);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (69, 'Shakira', 'She Wolf', 340234622);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (70, 'Bizarrap & Shakira', 'Shakira: Bzrp Music Sessions, Vol. 53', 1660098823);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (71, 'Imagine Dragons', 'Thunder', 1411629089);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (72, 'Imagine Dragons', 'Believer', 1411628233);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (73, 'Imagine Dragons', 'Radioactive', 1440873126);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (74, 'Imagine Dragons', 'Demons', 1440873339);
INSERT INTO public.song (id, artist_name, track_name, itunes_song_id) VALUES (75, 'Imagine Dragons', 'Whatever It Takes', 1411628148);